### ISSUE TITLE
munmap_chunk() error on handshake

### ISSUE THREAD

**Issue by Rjmoraza** [rlabrecque/Steamworks.NET-Example#3]
Hi!
My game is using the last stable steamworks.net with Unity 5.0.0 and when the game runs in linux it runs just fine, but if I launch the game from steam it crashes right after the Unity splash.
The error I have is:

    *** Error in `/home/rodolfo/.steam/steam/steamapps/common/Voxel Blast/VoxelBlast.x86': munmap_chunk(): invalid pointer: 0x0b8d3a70 ***

I'm using Ubuntu 14.04 LTS 32-bit version.
The very first thing the game does is checking if the SteamManager is initialized and right away asks for the player name.

    if (SteamManager.Initialized) 
    {
    	print ("Steam is initialized");
    	Library.playerName = SteamFriends.GetPersonaName();
    	string Name="";
    	AppId_t id = new AppId_t(395300);
    	SteamAppList.GetAppName(id, out Name, 256);
    	print("Name:" + Name);
    	print(Library.playerName + " " + SteamUtils.GetAppID() + Name);
    }
    else
    {
    	print ("Initializing Steam API");
    	SteamAPI.Init();
    	Library.playerName = SteamFriends.GetPersonaName();
    	string Name="";
    	AppId_t id = new AppId_t(395300);
    	SteamAppList.GetAppName(id, out Name, 256);
    	print("Name:" +Name);
    	print(Library.playerName+" "+SteamUtils.GetAppID()+Name);
    }

Do you have any insights regarding this issue?
Thanks a lot for your time!

**Comment by rlabrecque** [comment]
Hey @Rjmoraza, sorry for the late reply! I haven't seen anyone with this issue before, are you still running into it?

**Comment by Rjmoraza** [comment]
Hey Riley!
Thanks for the response.
I managed to fix it, it had nothing to do with steamworks.net, I'm sorry to have bothered you with this.
Apparently the issue was with some unity/mono libraries colliding with steam environment, it fixed after Unity update 5.2.1f1

**Comment by rlabrecque** [comment]
Awesome, glad to hear it! That was going to be my next suggestion!
