### ISSUE TITLE
How to retrieve leaderboards from steam

### ISSUE THREAD

**Issue by yakmyakmyakm** [rlabrecque/Steamworks.NET-Example#4]
Hi, 

Is there a way to get a leaderboard from steam and upload data to it?

I'm using c# and i'm not able to get the types to line up. like in the steamworks documentation https://partner.steamgames.com/documentation/bootstrap_leaderboards

I've tried this, and i'm not able to convert the api call to a leaderboard 

SteamLeaderboard_t currentLeaderBoard;
SteamAPICall_t apiCall = SteamUserStats.FindLeaderboard("Time");
LeaderboardFindResult_t findResult = (LeaderboardFindResult_t)apiCall;
currentLeaderBoard = findResult.m_hSteamLeaderboard;
SteamUserStats.UploadLeaderboardScore(currentLeaderBoard, ELeaderboardUploadScoreMethod.k_ELeaderboardUploadScoreMethodKeepBest, 100, null, 0);

**Comment by rlabrecque** [comment]
Hey @yakmyakmyakm, 

I'd recommend you read [this page](http://steamworks.github.io/gettingstarted/#steam-callresults) in the Steamworks.NET documentation, and look at [this project](https://github.com/rlabrecque/Steamworks.NET-Test/blob/master/Assets/Scripts/SteamUserStatsTest.cs#L198).

I hope that clears it up for you, if it doesn't the Steamworks Discussion forum would probably be a better place to ask this.

**Comment by yakmyakmyakm** [comment]
Thank you very much!

**Comment by nepitard** [comment]
@rlabrecque, may I ask you how do I retrieve leaderboards in array?
