### ISSUE TITLE
Unity Package manager error when importing steamworks

### ISSUE THREAD

**Issue by eriknielsen** [rlabrecque/Steamworks.NET-Example#9]
The following image shows which error I mean after cloning this project and opening with Unity 2020.3.10, is this just me or did something break?

![image](https://user-images.githubusercontent.com/7966092/123801961-0eac0200-d8eb-11eb-885c-b398f66a454a.png)

**Comment by rlabrecque** [comment]
Did this ever get fixed for you? I can't repro on 2020.3.10 at all on a fresh clone 😕

**Comment by eriknielsen** [comment]
Hi Riley, thanks for checking back in, I tested with another package and realized this import method doesn't work at all on my computer actually (no idea why), so closing this issue.
